name: dummy_lat_long_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  pin_code_fields: 7.4.0
  flutter_background_service: ^2.4.6
  flutter_background_service_android: 3.0.3
  flutter_local_notifications: ^13.0.0
  connectivity_plus: ^3.0.2
  geolocator: ^9.0.2
  http: ^0.13.5
  hive: ^2.2.3
  build_runner: ^2.3.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  path_provider: ^2.0.11
  get_storage: ^2.0.3
  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^1.0.0
  permission_handler: ^10.2.0
  flutter_launcher_icons: ^0.11.0
  fluttertoast: 8.1.2
  file_picker: 5.2.5
  http_parser: 4.0.2
  flutter: 
    sdk: flutter
  intl: ^0.18.0
  geocoding: ^2.0.5
  socket_io_client: ^2.0.1
  awesome_notifications: ^0.6.19
  camera: ^0.10.3+2
  infinite_scroll_pagination: ^3.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/icons/MagadhLogo.png
  ios: true
  min_sdk_android: 21

flutter: 
  uses-material-design: true

